import Head from "next/head";
import { AiOutlineMail, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import pic2 from "../public/pic2.png";
import frontend from "../public/download.jpg";
import backend from "../public/backend.jpg";
import comptetive from "../public/comptetive.jpg";
import Image from "next/image";
import proj1 from "../public/proj1.png";
import proj2 from "../public/proj2.jpg";
import hakimhub from "../public/hakimhub.jpg";
import atrons from "../public/atrons.jpg";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyed</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Email: se.yonas.assefa@gmail.com
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Yonas Assefa
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Fullstack Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Passionate full-stack developer with expertise in both front-end
              and back-end technologies, dedicated to crafting seamless digital
              experiences through code.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                href="https://www.linkedin.com/in/yonas-assefa-74334b224/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/Yonas-Assefa" target="_balnk">
                <AiFillGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image
                alt="my_image"
                src={pic2}
                layout="fill"
                objectFit="cover"
              />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white text-center underline">
              Services
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 text-center">
              I&apos;m here to bring your digital dreams to life and help your
              business thrive in the digital landscape. As a seasoned full-stack
              developer, I offer a wide range of services that empower your
              brand, streamline your operations, and enhance your online
              presence
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                className="rounded-md"
                src={frontend}
                width={100}
                height={100}
                alt="image1"
              />
              <h3 className="text-lg font-medium pb-2  ">
                Front-end Development
              </h3>
              <p className="py-2">
                Designing user-friendly front-end solutions that prioritize
                responsiveness and core design principles to meet your specific
                requirements.
              </p>
              <h4 className="pb-4 text-teal-600">Tools</h4>
              <p>
                <span className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 mx-2 border-none rounded-md">
                  React.js
                </span>
                <span className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 mx-2 border-none rounded-md">
                  Vue.js
                </span>
              </p>

              <p className="my-6">
                <span className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 mx-2 border-none rounded-md">
                  Next.js
                </span>
                <span className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 mx-2 border-none rounded-md">
                  Angular
                </span>
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={backend} width={100} height={100} alt="image2" />
              <h3 className="text-lg font-medium pb-2  ">
                Back-end Development
              </h3>
              <p className="py-2">
                Developing efficient and robust back-end systems that focus on
                data handling, security, and seamless functionality, tailored to
                your business needs.
              </p>
              <h4 className="pb-4 text-teal-600">Tools</h4>
              <p>
                <span className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 mx-2 border-none rounded-md">
                  Node.js
                </span>
                <span className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 mx-2 border-none rounded-md">
                  Django
                </span>
              </p>

              <p className="my-6">
                <span className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 mx-2 border-none rounded-md">
                  ASP.NET
                </span>
                <span className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 mx-2 border-none rounded-md">
                  Golang
                </span>
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={comptetive} width={100} height={100} alt="image3" />
              <h3 className="text-lg font-medium pb-2  ">
                Comptetive Programming
              </h3>
              <p className="py-2">
                Mastering competitive programming with precision, optimizing
                algorithms, and critical thinking to excel in coding
                competitions and real-world development challenges.
              </p>
              <h4 className=" pt-4 pb-4 text-teal-600">Tools</h4>
              <p>
                <span className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 mx-2 border-none rounded-md">
                  Leetcode
                </span>
                <span className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 mx-2 border-none rounded-md">
                  Codeforces
                </span>
              </p>

              <p className="my-6">
                <span className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 mx-2 border-none rounded-md">
                  HackerRank
                </span>
                <span className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 mx-2 border-none rounded-md">
                  GeeksForGeeks
                </span>
              </p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white text-center underline">
              Projects
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelancer and developer,
              I&apos;ve done remote work for
              <span className="text-teal-500"> agencies </span>
              and <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200"></p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 relative">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={proj1}
                alt="rateeat image"
              />
              <div className="absolute top-0 left-0 w-full h-full flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity duration-300">
                <p className="text-white bg-black bg-opacity-75 rounded-lg p-2 w-full h-full text-center">
                  <h2 className="text-3xl font-medium p-4  text-center">
                    Rateeat
                  </h2>
                  <p className="p-2 text-center">
                    Rateeat: A food discovery and ordering app that empowers
                    users to find nearby restaurants, read reviews, place
                    orders, and share their own ratings and feedback.
                  </p>
                  <a
                    className="bg-gradient-to-r from-cyan-700 text- to-teal-900 text-white px-2 py-1 my-4 border-none rounded-md ml-8"
                    href="https://rateeat.app/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Link
                  </a>
                </p>
              </div>
            </div>

            <div className="basis-1/3 flex-1 relative">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={proj2}
                alt="shemeta image"
              />
              <div className="absolute top-0 left-0 w-full h-full flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity duration-300">
                <p className="text-white bg-black bg-opacity-75 rounded-lg p-2 w-full h-full text-center">
                  <h2 className="text-3xl font-medium p-4  text-center">
                    Shemeta
                  </h2>
                  <p className="p-2 text-center">
                    Shemeta: Shemeta: Facilitating agricultural trade by
                    connecting farmers and small-scale enterprises directly with
                    consumers, offering fair prices and eliminating lengthy
                    market intermediaries.
                  </p>
                  <a
                    className="bg-gradient-to-r from-cyan-700 text- to-teal-900 text-white px-2 py-1 my-4 border-none rounded-md ml-8"
                    href="https://shemeta.netlify.app/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Link
                  </a>
                </p>
              </div>
            </div>

            <div className="basis-1/3 flex-1 relative">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={hakimhub}
                alt="hakimhub image"
              />
              <div className="absolute top-0 left-0 w-full h-full flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity duration-300">
                <p className="text-white bg-black bg-opacity-75 rounded-lg p-2 w-full h-full text-center">
                  <h2 className="text-3xl font-medium p-4  text-center">
                    HakimHub
                  </h2>
                  <p className="p-2 text-center">
                    HakimHub: Bridging healthcare gaps with a unified platform,
                    connecting doctors, patients, and medical institutions for
                    seamless, accessible healthcare services
                  </p>
                  <a
                    className="bg-gradient-to-r from-cyan-700 text- to-teal-900 text-white px-2 py-1 my-4 border-none rounded-md ml-8"
                    href="https://hakimhubweb.netlify.app/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Link
                  </a>
                </p>
              </div>
            </div>

            <div className="basis-1/3 flex-1 relative">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={atrons}
                alt="atrons image"
              />
              <div className="absolute top-0 left-0 w-full h-full flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity duration-300">
                <p className="text-white bg-black bg-opacity-75 rounded-lg p-2 w-full h-full text-center">
                  <h2 className="text-3xl font-medium p-4  text-center">
                    Atrons
                  </h2>
                  <p className="p-2 text-center">
                    Atrons: A platform where students can create free accounts
                    to access and share relevant resources from know sources.
                  </p>
                  <a
                    className="bg-gradient-to-r from-cyan-700 text- to-teal-900 text-white px-2 py-1 my-4 border-none rounded-md ml-8"
                    href="https://atrons.app/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Link
                  </a>
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
